[package]
name = "repair-rsv"
version = "0.1.0"
description = "One-click Sony RSV repair app"
authors = ["Repair RSV"]
edition = "2021"

[lib]
name = "repair_rsv_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.10.1", features = [] }
tauri-plugin-dialog = "2.7.0"
